# Generated by Django 2.1.5 on 2019-01-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cfd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENT_NAME', models.IntegerField(default=0, verbose_name='Client Name')),
                ('REMEDY_CLIENT_ID', models.IntegerField(default=0, verbose_name='REMEDY Client ID')),
                ('RETAIL_90_MAIL_RATES', models.CharField(max_length=13, verbose_name='Retail-90/Retail at Mail Rates')),
                ('RETAIL_90_MAIL_RATES_B_DS', models.IntegerField(default=0, verbose_name='Retail-90/Retail at Mail Rates Brand Days Supply Breakout')),
                ('RETAIL_90_MAIL_RATES_G_DS', models.IntegerField(default=0, verbose_name='Retail-90/Retail at Mail Rates Generic Days Supply Breakout')),
                ('GUAR_BR_IZBD_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail Brand AWP Discount (including ZBDs)')),
                ('GUAR_BR_EZBD_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail Brand AWP Discount (excluding ZBDs)')),
                ('GUAR_GR_IZBD_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail Generic AWP Discount (including ZBDs)')),
                ('GUAR_GR_EZBD_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail Generic AWP Discount (excluding ZBDs)')),
                ('GUAR_BR_DISP_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail Brand Dispensing Fee')),
                ('GUAR_GR_DISP_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail Generic Dispensing Fee')),
                ('GUAR_RETAIL_ADMIN_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail Admin Fee')),
                ('GUAR_RETAIL_REBATE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='     Rebate $')),
                ('GUAR_BR90_IZBD_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail-90 Brand AWP Discount (including ZBDs)')),
                ('GUAR_BR90_EZBD_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail-90 Brand AWP Discount (excluding ZBDs)')),
                ('GUAR_GR90_IZBD_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail-90 Generic AWP Discount (including ZBDs)')),
                ('GUAR_GR90_EZBD_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail-90 Generic AWP Discount (excluding ZBDs)')),
                ('GUAR_BR90_DISP_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail-90 Brand Dispensing Fee')),
                ('GUAR_GR90_DISP_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail-90 Generic Dispensing Fee')),
                ('GUAR_R90_ADMIN_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Retail-90 Admin Fee')),
                ('GUAR_BM_IZBD_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Mail Brand AWP Discount (including ZBDs)')),
                ('GUAR_BM_EZBD_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Mail Brand AWP Discount (excluding ZBDs)')),
                ('GUAR_GM_IZBD_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Mail Generic AWP Discount (including ZBDs)')),
                ('GUAR_GM_EZBD_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Mail Generic AWP Discount (excluding ZBDs)')),
                ('GUAR_BM_DISP_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Mail Brand Dispensing Fee')),
                ('GUAR_GM_DISP_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Mail Generic Dispensing Fee')),
                ('GUAR_MAIL_ADMIN_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Mail Admin Fee')),
                ('GUAR_SPC_BR_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Specialty Brand AWP Discount - Retail')),
                ('GUAR_SPC_GR_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Specialty Generic AWP Discount - Retail')),
                ('GUAR_SPC_BR_DISP_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Specialty Brand Dispensing Fee - Retail')),
                ('GUAR_SPC_GR_DISP_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Specialty Generic Dispensing Fee - Retail')),
                ('GUAR_SPC_RETAIL_ADMIN_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Specialty Admin Fee - Retail')),
                ('GUAR_SPC_SRX_B_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Specialty Brand AWP Discount - SRx')),
                ('GUAR_SPC_SRX_G_DCT', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Specialty Generic AWP Discount - SRx')),
                ('GUAR_SPC_G_SRX_DISP_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Specialty Generic Dispensing Fee - SRx')),
                ('GUAR_SPC_B_SRX_DISP_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Specialty Brand Dispensing Fee - SRx')),
                ('GUAR_SPC_SRX_ADMIN_FEE', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='Specialty Admin Fee - SRx')),
                ('IE_SSG', models.CharField(max_length=30, verbose_name='SSG')),
                ('IE_ZBD', models.CharField(max_length=37, verbose_name='ZBD')),
                ('IE_UAC', models.CharField(max_length=30, verbose_name='U&C')),
                ('IE_GENERICS_UNDER_EXCLUSIVITY', models.CharField(max_length=30, verbose_name='Generics under Exclusivity')),
                ('IE_AUTHORIZED_GENERICS', models.CharField(max_length=37, verbose_name='Authorized Generics')),
                ('IE_PATENT_LITIGATED_GENERICS', models.CharField(max_length=37, verbose_name='Patent Litigated Generics')),
                ('IE_MAC_GENERICS', models.CharField(max_length=37, verbose_name='MAC Generics')),
                ('IE_NON_MAC_GENERICS', models.CharField(max_length=37, verbose_name='Non-MAC Generics')),
                ('IE_MAC_BRANDS', models.CharField(max_length=37, verbose_name='MAC Brands ')),
                ('IE_ADJUSTMENTS', models.CharField(max_length=43, verbose_name='Adjustments')),
                ('IE_COB_SECONDARY_CLAIMS', models.CharField(max_length=30, verbose_name='COB/Secondary Claims')),
                ('IE_DMR_CLAIMS', models.CharField(max_length=30, verbose_name='Direct Member Reimbursement (DMR) Claims')),
                ('IE_EXCLUDED_PROVIDERS', models.CharField(max_length=30, verbose_name='Excluded Providers (e.g. VA, I/T/U, nursing home, long-term care, in-house, on-site)')),
                ('IE_REJECTS', models.CharField(max_length=30, verbose_name='Rejects')),
                ('IE_REVERSALS', models.CharField(max_length=30, verbose_name='Reversals')),
                ('IE_SUBROGATION', models.CharField(max_length=30, verbose_name='Subrogation')),
                ('IE_NON_DRUG_ITEMS', models.CharField(max_length=30, verbose_name='Non Drug Items')),
                ('IE_OTC', models.CharField(max_length=30, verbose_name='Over-The-Counter (OTC)')),
                ('IE_PRICING_ERROR_THRESHOLDS', models.CharField(max_length=23, verbose_name='Pricing error thresholds (claims excluded from the analysis)')),
                ('IE_DAW_5', models.CharField(max_length=52, verbose_name='DAW 5')),
                ('IE_COMPOUNDS', models.CharField(max_length=37, verbose_name='Compounds')),
                ('M_RATES_APPLY_TO_ALL_M', models.CharField(max_length=30, verbose_name='Mail Rates Apply to All Mail Claims')),
                ('M_RATE_BREAKOUT', models.CharField(max_length=1, verbose_name='Mail Rate Breakout')),
                ('LDD_DISC', models.DecimalField(decimal_places=9, max_digits=20, verbose_name='LDD (Effective Discount)')),
                ('LDD_REBATE', models.CharField(max_length=30, verbose_name='LDD (Rebates)')),
                ('BIOSIMILAR_DISC', models.CharField(max_length=23, verbose_name='Biosimilar (Effective Discount)')),
                ('OBSOLETE_NDCS', models.CharField(max_length=23, verbose_name='Obsolete NDCs')),
            ],
        ),
    ]
