# Generated by Django 2.1.5 on 2019-01-25 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfd',
            name='CLIENT_NAME',
            field=models.CharField(max_length=255, verbose_name='Client Name'),
        ),
    ]
