# Generated by Django 2.1.5 on 2019-01-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0002_auto_20190125_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfd',
            name='BIOSIMILAR_DISC',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Biosimilar (Effective Discount)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_ADJUSTMENTS',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Adjustments'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_AUTHORIZED_GENERICS',
            field=models.CharField(choices=[('Include in GER - Explicit in Contract', 'Include in GER - Explicit in Contract'), ('Include in GER - Assumed by CE', 'Include in GER - Assumed by CE'), ('Include in BER - Explicit in Contract', 'Include in BER - Explicit in Contract'), ('Include in BER - Assumed by CE', 'Include in BER - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Authorized Generics'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_COB_SECONDARY_CLAIMS',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='COB/Secondary Claims'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_COMPOUNDS',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Compounds'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_DAW_5',
            field=models.CharField(choices=[('Include in GER - Explicit in Contract', 'Include in GER - Explicit in Contract'), ('Include in GER - Assumed by CE', 'Include in GER - Assumed by CE'), ('Include in BER - Explicit in Contract', 'Include in BER - Explicit in Contract'), ('Include in BER - Assumed by CE', 'Include in BER - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=52, verbose_name='DAW 5'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_DMR_CLAIMS',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Direct Member Reimbursement (DMR) Claims'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_EXCLUDED_PROVIDERS',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=30, verbose_name='Excluded Providers (e.g. VA, I/T/U, nursing home, long-term care, in-house, on-site)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_GENERICS_UNDER_EXCLUSIVITY',
            field=models.CharField(choices=[('Include in GER - Explicit in Contract', 'Include in GER - Explicit in Contract'), ('Include in GER - Assumed by CE', 'Include in GER - Assumed by CE'), ('Include in BER - Explicit in Contract', 'Include in BER - Explicit in Contract'), ('Include in BER - Assumed by CE', 'Include in BER - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Generics under Exclusivity'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_MAC_BRANDS',
            field=models.CharField(choices=[('Include in GER - Explicit in Contract', 'Include in GER - Explicit in Contract'), ('Include in GER - Assumed by CE', 'Include in GER - Assumed by CE'), ('Include in BER - Explicit in Contract', 'Include in BER - Explicit in Contract'), ('Include in BER - Assumed by CE', 'Include in BER - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='MAC Brands '),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_MAC_GENERICS',
            field=models.CharField(choices=[('Include in GER - Explicit in Contract', 'Include in GER - Explicit in Contract'), ('Include in GER - Assumed by CE', 'Include in GER - Assumed by CE'), ('Include in BER - Explicit in Contract', 'Include in BER - Explicit in Contract'), ('Include in BER - Assumed by CE', 'Include in BER - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='MAC Generics'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_NON_DRUG_ITEMS',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Non Drug Items'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_NON_MAC_GENERICS',
            field=models.CharField(choices=[('Include in GER - Explicit in Contract', 'Include in GER - Explicit in Contract'), ('Include in GER - Assumed by CE', 'Include in GER - Assumed by CE'), ('Include in BER - Explicit in Contract', 'Include in BER - Explicit in Contract'), ('Include in BER - Assumed by CE', 'Include in BER - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=37, verbose_name='Non-MAC Generics'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_OTC',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Over-The-Counter (OTC)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_PATENT_LITIGATED_GENERICS',
            field=models.CharField(choices=[('Include in GER - Explicit in Contract', 'Include in GER - Explicit in Contract'), ('Include in GER - Assumed by CE', 'Include in GER - Assumed by CE'), ('Include in BER - Explicit in Contract', 'Include in BER - Explicit in Contract'), ('Include in BER - Assumed by CE', 'Include in BER - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=37, verbose_name='Patent Litigated Generics'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_PRICING_ERROR_THRESHOLDS',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Pricing error thresholds (claims excluded from the analysis)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_REJECTS',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Rejects'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_REVERSALS',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Reversals'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_SSG',
            field=models.CharField(choices=[('Include in GER - Explicit in Contract', 'Include in GER - Explicit in Contract'), ('Include in GER - Assumed by CE', 'Include in GER - Assumed by CE'), ('Include in BER - Explicit in Contract', 'Include in BER - Explicit in Contract'), ('Include in BER - Assumed by CE', 'Include in BER - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='SSG'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_SUBROGATION',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Subrogation'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_UAC',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='U&C'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_ZBD',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='ZBD'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='LDD_REBATE',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='LDD (Rebates)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='M_RATES_APPLY_TO_ALL_M',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=50, verbose_name='Mail Rates Apply to All Mail Claims'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='M_RATE_BREAKOUT',
            field=models.IntegerField(max_length=1, verbose_name='Mail Rate Breakout'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='OBSOLETE_NDCS',
            field=models.CharField(choices=[('Include - Explicit in Contract', 'Include - Explicit in Contract'), ('Include - Assumed by CE', 'Include - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], max_length=50, verbose_name='Obsolete NDCs'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='RETAIL_90_MAIL_RATES',
            field=models.CharField(choices=[('Y - Retail-90', 'Y - Retail-90'), ('Y - Retail at Mail Rates', 'Y - Retail at Mail Rates'), ('Y - Retail-90 & Retail at Mail Rates', 'Y - Retail-90 & Retail at Mail Rates'), ('N', 'N')], max_length=13, verbose_name='Retail-90/Retail at Mail Rates'),
        ),
    ]
