# Generated by Django 2.1.5 on 2019-01-31 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0003_auto_20190125_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cfd',
            options={'verbose_name': 'Client Financial Record', 'verbose_name_plural': 'Client Financial Records'},
        ),
        migrations.AddField(
            model_name='cfd',
            name='END_DATE',
            field=models.DateField(default=datetime.date.today, verbose_name='Contract End Date'),
        ),
        migrations.AddField(
            model_name='cfd',
            name='START_DATE',
            field=models.DateField(default=datetime.date.today, verbose_name='Contract Start Date'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_BM_DISP_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Mail Brand Dispensing Fee'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_BM_EZBD_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Mail Brand AWP Discount (excluding ZBDs)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_BM_IZBD_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Mail Brand AWP Discount (including ZBDs)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_BR90_DISP_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail-90 Brand Dispensing Fee'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_BR90_EZBD_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail-90 Brand AWP Discount (excluding ZBDs)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_BR90_IZBD_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail-90 Brand AWP Discount (including ZBDs)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_BR_DISP_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail Brand Dispensing Fee'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_BR_EZBD_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail Brand AWP Discount (excluding ZBDs)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_BR_IZBD_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail Brand AWP Discount (including ZBDs)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_GM_DISP_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Mail Generic Dispensing Fee'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_GM_EZBD_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Mail Generic AWP Discount (excluding ZBDs)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_GM_IZBD_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Mail Generic AWP Discount (including ZBDs)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_GR90_DISP_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail-90 Generic Dispensing Fee'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_GR90_EZBD_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail-90 Generic AWP Discount (excluding ZBDs)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_GR90_IZBD_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail-90 Generic AWP Discount (including ZBDs)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_GR_DISP_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail Generic Dispensing Fee'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_GR_EZBD_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail Generic AWP Discount (excluding ZBDs)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_GR_IZBD_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail Generic AWP Discount (including ZBDs)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_MAIL_ADMIN_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Mail Admin Fee'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_R90_ADMIN_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail-90 Admin Fee'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_RETAIL_ADMIN_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Retail Admin Fee'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_RETAIL_REBATE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='     Rebate $'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_SPC_BR_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Specialty Brand AWP Discount - Retail'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_SPC_BR_DISP_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Specialty Brand Dispensing Fee - Retail'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_SPC_B_SRX_DISP_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Specialty Brand Dispensing Fee - SRx'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_SPC_GR_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Specialty Generic AWP Discount - Retail'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_SPC_GR_DISP_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Specialty Generic Dispensing Fee - Retail'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_SPC_G_SRX_DISP_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Specialty Generic Dispensing Fee - SRx'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_SPC_RETAIL_ADMIN_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Specialty Admin Fee - Retail'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_SPC_SRX_ADMIN_FEE',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Specialty Admin Fee - SRx'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_SPC_SRX_B_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Specialty Brand AWP Discount - SRx'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='GUAR_SPC_SRX_G_DCT',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Specialty Generic AWP Discount - SRx'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='LDD_DISC',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='LDD (Effective Discount)'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='M_RATE_BREAKOUT',
            field=models.IntegerField(verbose_name='Mail Rate Breakout'),
        ),
    ]
