# Generated by Django 2.1.5 on 2019-01-31 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0004_auto_20190131_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfd',
            name='CONTRACT_DESCRIPTION',
            field=models.TextField(blank=True, max_length=500, verbose_name='Contract Description'),
        ),
        migrations.AddField(
            model_name='cfd',
            name='CONTRACT_TYPE',
            field=models.CharField(choices=[('Baseline Remedy', 'Baseline Remedy'), ('Previous PBM Contract', 'Previous PBM Contract'), ('Standard', 'Standard')], default='Standard', max_length=25, verbose_name='Contract Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cfd',
            name='END_DATE',
            field=models.DateField(default=datetime.date(2020, 1, 31), verbose_name='Contract End Date'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='IE_AUTHORIZED_GENERICS',
            field=models.CharField(choices=[('Include in GER - Explicit in Contract', 'Include in GER - Explicit in Contract'), ('Include in GER - Assumed by CE', 'Include in GER - Assumed by CE'), ('Include in BER - Explicit in Contract', 'Include in BER - Explicit in Contract'), ('Include in BER - Assumed by CE', 'Include in BER - Assumed by CE'), ('Exclude - Explicit in Contract', 'Exclude - Explicit in Contract'), ('Exclude - Assumed by CE', 'Exclude - Assumed by CE')], help_text='Authorized generics are prescription drugs produced by brand pharmaceutical companies and marketed under a private label, at generic prices. RA identified via Medispan', max_length=50, verbose_name='Authorized Generics'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='START_DATE',
            field=models.DateField(default=datetime.date(2019, 1, 31), verbose_name='Contract Start Date'),
        ),
    ]
