# Generated by Django 2.1.5 on 2019-01-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0006_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENT_ID', models.IntegerField(verbose_name='Client ID')),
                ('CLIENT_NAME', models.CharField(max_length=255, verbose_name='Client Name')),
                ('CLIENT_REPORT_NAME', models.CharField(max_length=255, verbose_name='Client Report Name')),
                ('IS_CLIENT_FLAG', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], verbose_name='Is Client?')),
                ('PARENT_ID', models.IntegerField(null=True, verbose_name='Parent')),
                ('ACTIVE_CLIENT', models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], verbose_name='Active Client?')),
                ('PRIMARY_CONSULTANT_ID', models.IntegerField(verbose_name='Primary Consultant ID')),
                ('PRIMARY_CONSULTANT', models.CharField(max_length=255, verbose_name='Primary Consultant Name')),
                ('COALITION', models.CharField(max_length=255, verbose_name='Coalition')),
                ('BROKER', models.CharField(max_length=255, verbose_name='Broker')),
                ('BOB_FLAG', models.CharField(max_length=255, verbose_name='BOB_FLAG')),
            ],
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
