# Generated by Django 2.1.5 on 2019-01-31 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0007_auto_20190131_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfd',
            name='REMEDY_CLIENT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfd.client'),
        ),
    ]
