# Generated by Django 2.1.5 on 2019-01-31 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0009_auto_20190131_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfd',
            name='CLIENT',
            field=models.ForeignKey(limit_choices_to={'ACTIVE_CLIENT': True}, on_delete=django.db.models.deletion.PROTECT, to='cfd.client'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='RETAIL_90_MAIL_RATES',
            field=models.CharField(choices=[('Y - Retail-90', 'Y - Retail-90'), ('Y - Retail at Mail Rates', 'Y - Retail at Mail Rates'), ('Y - Retail-90 & Retail at Mail Rates', 'Y - Retail-90 & Retail at Mail Rates'), ('N', 'N')], max_length=50, verbose_name='Retail-90/Retail at Mail Rates'),
        ),
    ]
