# Generated by Django 2.1.5 on 2019-02-01 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0010_auto_20190131_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfd',
            name='NON_SPC_CLASSES',
            field=models.CharField(choices=[('Transplant', 'Transplant'), ('Hepatitis B', 'Hepatitis B'), ('CMV Agents', 'CMV Agents'), ('HIV', 'HIV'), ('Anticoagulants', 'Anticoagulants'), ('Hepatitis C', 'Hepatitis C'), ('PCSK9', 'PCSK9')], default='Change Me', max_length=20, verbose_name='Therapy Classes Not Considered Specialty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cfd',
            name='END_DATE',
            field=models.DateField(default=datetime.date(2020, 2, 1), verbose_name='Contract End Date'),
        ),
        migrations.AlterField(
            model_name='cfd',
            name='START_DATE',
            field=models.DateField(default=datetime.date(2019, 2, 1), verbose_name='Contract Start Date'),
        ),
    ]
